stages:
  - linting
  - build
  - deploy

include:
  - 'vars.yaml'

debug:
  stage: linting
  script:
    - echo "${DOCKER_REPO}:${IMAGE_TAG}"

lint-docker:
  stage: linting
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint Dockerfile
  allow_failure: true

include:
  - project: 'anestesia_01/dos-30-genreral-pipelines'
    ref: main
    file: 'build-kaniko.yaml'
  - project: 'anestesia_01/dos-30-genreral-pipelines'
    ref: main
    file: 'deploy-standalone.yaml'

